# Generated by Django 2.1.5 on 2019-03-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaturalPersons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('apePater', models.CharField(max_length=30)),
                ('apeMater', models.CharField(max_length=30)),
                ('edad', models.CharField(max_length=30)),
                ('fecNacim', models.DateField()),
                ('dni', models.IntegerField(max_length=8)),
                ('email', models.EmailField(max_length=50)),
                ('celular', models.IntegerField(max_length=9)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_imagess')),
                ('estado', models.IntegerField(max_length=1)),
            ],
        ),
    ]
