# Generated by Django 2.1.5 on 2019-03-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalpersons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalpersons',
            name='estado',
            field=models.IntegerField(choices=[('1', 'Hombre'), ('2', 'Mujer')], max_length=1),
        ),
    ]
