# Generated by Django 2.1.5 on 2019-03-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalpersons', '0002_auto_20190317_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalpersons',
            name='estado',
            field=models.IntegerField(choices=[('1', 'Hombre'), ('2', 'Mujer'), ('3', 'Otros')], max_length=1),
        ),
    ]
