# Generated by Django 2.1.5 on 2019-03-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalpersons', '0003_auto_20190317_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalpersons',
            name='estado',
            field=models.IntegerField(max_length=1),
        ),
    ]
