# Generated by Django 2.1.5 on 2019-07-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalpersons', '0004_auto_20190317_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalpersons',
            name='celular',
            field=models.IntegerField(verbose_name=9),
        ),
        migrations.AlterField(
            model_name='naturalpersons',
            name='estado',
            field=models.IntegerField(verbose_name=1),
        ),
    ]
