# Generated by Django 2.1.5 on 2019-07-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturalpersons', '0005_auto_20190727_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='naturalpersons',
            name='dni',
            field=models.IntegerField(verbose_name=8),
        ),
    ]
