# Generated by Django 2.1.5 on 2019-01-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCategoria', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('tipoCategoria', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=3)),
            ],
        ),
    ]
