# Generated by Django 2.1.5 on 2019-07-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_auto_20190317_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='estado',
            field=models.IntegerField(verbose_name=1),
        ),
    ]
