# Generated by Django 2.1.5 on 2019-08-11 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hora_reserv', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
    ]
