# Generated by Django 2.1.5 on 2019-07-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocalizations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('lng', models.CharField(max_length=100)),
                ('arrastrable', models.CharField(max_length=5)),
                ('estado', models.CharField(max_length=1)),
            ],
        ),
    ]
