# Generated by Django 2.1.5 on 2019-08-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocalizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geolocalizations',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_img'),
        ),
    ]
